"""add shipping fields to orders

Revision ID: 5d8d9799ab85
Revises: 3022f2a9b60f
Create Date: 2026-04-03 19:55:11.203657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8d9799ab85'
down_revision: Union[str, Sequence[str], None] = '3022f2a9b60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('shipping_cost', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('tracking_code', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'tracking_code')
    op.drop_column('orders', 'is_delivered')
    op.drop_column('orders', 'shipping_cost')
    op.drop_column('orders', 'address_id')
    # ### end Alembic commands ###
