"""replace stripe with paystack

Revision ID: 8bc7ef4a2d6e
Revises: b85fdbc18f1a
Create Date: 2026-04-03 10:07:14.519633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc7ef4a2d6e'
down_revision: Union[str, Sequence[str], None] = 'b85fdbc18f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('reference', sa.String(), nullable=True))
    op.drop_constraint('payments_payment_intent_id_key', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.drop_column('payments', 'payment_intent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.create_unique_constraint('payments_payment_intent_id_key', 'payments', ['payment_intent_id'])
    op.drop_column('payments', 'reference')
    # ### end Alembic commands ###
